### ISSUE TITLE
Not unpacked by Kavanoz

### ISSUE THREAD

**Issue by cryptax** [eybisi/kavanoz#5]
[This other malicious sample of Android/BianLian](https://www.virustotal.com/gui/file/2e84fd3484fcde105c437f1c0366954f4bdee7c1d3b334e2daa366a6592e4432) is not unpacked by Kavanoz. 

sha256: `2e84fd3484fcde105c437f1c0366954f4bdee7c1d3b334e2daa366a6592e4432`

```
# kavanoz 2e84fd3484fcde105c437f1c0366954f4bdee7c1d3b334e2daa366a6592e4432.apk 
⚠ Sample is not packed
❌ Cannot unpack
```

APKiD says it is packed with _DexProtector_, but I'm not sure it's really DexProtector. 

```
# apkid 2e84fd3484fcde105c437f1c0366954f4bdee7c1d3b334e2daa366a6592e4432.apk 
[+] APKiD 2.1.5 :: from RedNaga :: rednaga.io
[*] 2e84fd3484fcde105c437f1c0366954f4bdee7c1d3b334e2daa366a6592e4432.apk
 |-> packer : DexProtector
[*] 2e84fd3484fcde105c437f1c0366954f4bdee7c1d3b334e2daa366a6592e4432.apk!classes.dex
 |-> anti_vm : possible Build.SERIAL check, possible VM check
 |-> compiler : dexlib 2.x
```

You can unpack quite easily with a Frida script that prevents file deletion. The unpacked payload will be in `/storage/emulated/0/Android/obb/com.grand.snail/dp/dp-a.a`. Or Medusa with `file_system/prevent_delete` module.

FYI, there is no emergency, I'm just sending in the samples that fail with Kavanoz but take time you need to handle them (or not!).

**Comment by eybisi** [comment]
Should be fixed in [commit](https://github.com/eybisi/kavanoz/commit/14e98e84101b9a2635c07b76030e425d7c868b6f)

**Comment by eybisi** [comment]
Btw main reason it says "sample is not packed" because androguard returns 0 activites/receivers/services, since androguard can't parse androidmanifest.xml file.

**Comment by cryptax** [comment]
Well done! It works great :)

```
kavanoz 2e84fd3484fcde105c437f1c0366954f4bdee7c1d3b334e2daa366a6592e4432.apk 
⚠ Sample is not packed
✨ Unpacked succesfully!
Plugin tag : loader.multidex 
Plugin description : Unpacker for multidex variants 
Output file : ./external-8ccb1cd1.dex
```

It even fixed another malware I was about to report :)
