### ISSUE TITLE
Kavanoz asks for androguard 3.3.5 but Quark requests androguard 3.4.0a1

### ISSUE THREAD

**Issue by cryptax** [eybisi/kavanoz#6]
Your requirement file asks for `androguard==3.3.5`, which is incompatible with another tool [Quark Engine](https://github.com/quark-engine/quark-engine). While I agree it's not really your business to be compatible with other tools, actually it seems to me that Kavanoz works fine with Androguard 3.4.0a1, so you can probably modify the requirement file to ask for `>=3.3.5`.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
quark-engine 23.9.1 requires androguard==3.4.0a1, but you have androguard 3.3.5 which is incompatible.
```

**Comment by eybisi** [comment]
Done!
